apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api
  namespace: naturalantibody-platform
  labels:
    app: search-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-api
  template:
    metadata:
      labels:
        app: search-api
    spec:
      containers:
        - name: search-api
          image: 071253002612.dkr.ecr.eu-central-1.amazonaws.com/naturalantibody-antibody-databases-repository-public:v1.0.0
          command: ["poetry", "run", "uvicorn", "antibody_databases.infrastructure.app:fastapi_app", "--host", "0.0.0.0"]
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-search
                  key: password
            - name: DB_HOST
              value: mongodb://search:$(MONGODB_PASSWORD)@mongodb-svc.naturalantibody-platform-mongo.svc.cluster.local/search?ssl=false&authSource=admin
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBITMQ_DEFAULT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: host
            - name: CELERY_BROKER_URL
              value: amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_USER_PASSWORD)@$(RABBITMQ_HOST)/
            - name: CELERY_RESULT_BACKEND
              value: antibody_databases.infrastructure.celery.backend:ExtendedMongoBackend+$(DB_HOST)
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: token-secret
                  key: password
            - name: REDIS_URL
              value: redis://redis.naturalantibody-platform-redis.svc.cluster.local:6379
            - name: USERS_API_URL
              value: http://users.naturalantibody-platform.svc.cluster.local
            - name: QUEUES
              value: search-events
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 1024Mi
      nodeSelector:
        kubernetes.io/os: linux

      tolerations:
      - key: "eks.amazonaws.com/compute-type"
        operator: "Equal"
        value: "fargate"
        effect: "NoSchedule"

---

apiVersion: v1
kind: Service
metadata:
  namespace: naturalantibody-platform
  name: search-api
  labels:
    app: search-api
spec:
  selector:
    app: search-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
