apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-api
  namespace: naturalantibody-platform
  labels:
    app: mailer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer-api
  template:
    metadata:
      labels:
        app: mailer-api
    spec:
      containers:
        - name: mailer-api
          image: 071253002612.dkr.ecr.eu-central-1.amazonaws.com/naturalantibody-mailer-repository-repository-public:v1.0.0
          command: ["poetry", "run", "uvicorn", "mailer.infrastructure.app:app", "--host", "0.0.0.0"]
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-mailer
                  key: password
            - name: MONGODB_URL
              value: mongodb://mailer:$(MONGODB_PASSWORD)@mongodb-svc.naturalantibody-platform-mongo.svc.cluster.local/mailer?ssl=false&authSource=admin
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBITMQ_DEFAULT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: host
            - name: CELERY_BROKER_URL
              value: amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_USER_PASSWORD)@$(RABBITMQ_HOST)/
            - name: CELERY_RESULT_BACKEND
              value: mailer.infrastructure.celery_utils.backend:ExtendedMongoBackend+$(MONGODB_URL)
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: token-secret
                  key: password
            - name: REDIS_URL
              value: redis://redis.example-redis.svc.cluster.local
            - name: USERS_API_URL
              value: http://users.naturalantibody-platform.svc.cluster.local
            - name: USE_SSL
              value: "false"
            - name: SMTP_SERVER
              value: smtp.gmail.com
            - name: PORT
              value: '587'
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: client-configuration
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: client-configuration
                  key: password
            - name: SENDER_EMAIL
              value: "no-reply@example.com"
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 1024Mi
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "eks.amazonaws.com/compute-type"
        operator: "Equal"
        value: "fargate"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  namespace: naturalantibody-platform
  name: mailer-api
  labels:
    app: mailer-api
spec:
  selector:
    app: mailer-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
