apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: naturalantibody-platform
  labels:
    app: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
        - name: docs
          image: 071253002612.dkr.ecr.eu-central-1.amazonaws.com/naturalantibody-docs-repository-public:latest
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 3002
            initialDelaySeconds: 120
            periodSeconds: 60
          startupProbe:
            httpGet:
              path: /
              port: 3002
            failureThreshold: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: token-secret
                  key: password
            - name: NEXT_PUBLIC_UI_URL
              value: https://platform.example.com
            - name: APP_URL
              value: https://docs.platform.example.com
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 100m
              memory: 384Mi
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "eks.amazonaws.com/compute-type"
        operator: "Equal"
        value: "fargate"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  namespace: naturalantibody-platform
  name: docs
  labels:
    app: docs
  annotations:
    alb.ingress.kubernetes.io/success-codes: 200,307
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '30'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '5'
spec:
  selector:
    app: docs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
